# Generated by Django 2.2.2 on 2019-06-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('verify_token', models.TextField(max_length=300, unique=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
