# Generated by Django 2.2.2 on 2019-06-08 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_message_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_manual_intervention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='source',
            field=models.CharField(choices=[('fb', 'fb'), ('email', 'email'), ('app', 'app')], default='app', max_length=255),
        ),
    ]
