# Generated by Django 2.2.2 on 2019-06-08 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_auto_20190608_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
