# Generated by Django 2.2.2 on 2019-06-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golocals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
    ]
