# Generated by Django 2.2.2 on 2019-06-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golocals', '0002_initiative_shares_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='cover',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
